exclude: '^docs/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
    - id: build-docs
      args: ['--cache-dir', 'docs/doctrees', '--html-dir', 'docs/html', '--source-dir', 'docs/']
      language_version: python3
      additional_dependencies: ['numpy', 'tqdm']
